export const SET_GAME_STATUS = 'SET_GAME_STATUS';
export const SET_PRICE_TABLE = 'SET_PRICE_TABLE';

export const INIT_STATIC_INFORMATION = 'INIT_STATIC_INFORMATION';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_INVENTORY = 'SET_INVENTORY';
